cis_benchmarks:
  # Public Bucket Scanning
  - id: "5.1"
    title: "Ensure That Cloud Storage Bucket Is Not Anonymously or Publicly Accessible (Automated)"
    profile_applicability: "Level 1"
    description: "It is recommended that IAM policy on Cloud Storage bucket does not allow anonymous or public access."
    rationale: "Allowing anonymous or public access grants permissions to anyone to access bucket content. Such access might not be desired if you are storing any sensitive data."
    audit:
      gcloud_command: "gsutil iam get gs://BUCKET_NAME"
    remediation:
      steps:
        - "Remove allUsers and allAuthenticatedUsers from the IAM policy of the bucket."
        - "Use the following commands to remove public access:"
        - "gsutil iam ch -d allUsers gs://BUCKET_NAME"
        - "gsutil iam ch -d allAuthenticatedUsers gs://BUCKET_NAME"
    prevention:
      steps:
        - "Prevent buckets from becoming publicly accessible by setting up the Domain restricted sharing organization policy."
    default_value: "By default, storage buckets are not publicly shared."
    references:
      - "https://cloud.google.com/storage/docs/access-control/iam-reference"
      - "https://cloud.google.com/storage/docs/access-control/making-data-public"
      - "https://cloud.google.com/storage/docs/gsutil/commands/iam"

  - id: "5.2"
    title: "Ensure That Cloud Storage Buckets Have Uniform Bucket-Level Access Enabled (Automated)"
    profile_applicability: "Level 2"
    description: "It is recommended that uniform bucket-level access is enabled on Cloud Storage buckets."
    rationale: "Uniform bucket-level access simplifies permission management by granting access exclusively through Cloud IAM, disabling ACLs."
    audit:
      gcloud_command: "gsutil uniformbucketlevelaccess get gs://BUCKET_NAME/"
    remediation:
      steps:
        - "Enable uniform bucket-level access using the following command:"
        - "gsutil uniformbucketlevelaccess set on gs://BUCKET_NAME/"
    prevention:
      steps:
        - "Set up an Organization Policy to enforce uniform bucket-level access for new buckets."
    default_value: "By default, Cloud Storage buckets do not have uniform bucket-level access enabled."
    references:
      - "https://cloud.google.com/storage/docs/uniform-bucket-level-access"
      - "https://cloud.google.com/storage/docs/using-uniform-bucket-level-access"
      - "https://cloud.google.com/storage/docs/setting-org-policies#uniform-bucket"

  # Over-Permissive IAM Account Scanning
  - id: "1.4"
    title: "Ensure That There Are Only GCP-Managed Service Account Keys for Each Service Account (Automated)"
    profile_applicability: "Level 1"
    description: "Ensure only GCP-managed service account keys exist."
    rationale: "GCP-managed keys reduce the risk of key compromise compared to user-managed keys."
    audit:
      gcloud_command: "gcloud iam service-accounts keys list --iam-account=SERVICE_ACCOUNT_EMAIL --managed-by=user"
    remediation:
      steps:
        - "Delete any user-managed keys for service accounts using the following command:"
        - "gcloud iam service-accounts keys delete --iam-account=<user-managed-service-account-EMAIL> <KEY-ID>"
    prevention:
      steps:
        - "Disable service account key creation through the Disable service account key creation Organization policy."
    default_value: "By default, there are no user-managed keys created for user-managed service accounts."
    references:
      - "https://cloud.google.com/iam/docs/understanding-service-accounts#managing_service_account_keys"

  - id: "1.5"
    title: "Ensure That Service Account Has No Admin Privileges (Automated)"
    profile_applicability: "Level 1"
    description: "Ensure service accounts do not have admin privileges."
    rationale: "Service accounts with admin privileges can lead to privilege escalation and unauthorized access."
    audit:
      gcloud_command: "gcloud projects get-iam-policy PROJECT_ID --format=json | jq '.bindings[] | select(.role | contains(\"roles/editor\") or contains(\"roles/owner\") or contains(\"roles/admin\"))'"
    remediation:
      steps:
        - "Remove admin roles from service accounts in the IAM policy."
    default_value: "By default, service accounts do not have admin privileges unless explicitly granted."
    references:
      - "https://cloud.google.com/iam/docs/understanding-roles"

  - id: "1.6"
    title: "Ensure That IAM Users Are Not Assigned the Service Account User or Service Account Token Creator Roles at Project Level (Automated)"
    profile_applicability: "Level 1"
    description: "Ensure IAM users are not assigned the Service Account User or Service Account Token Creator roles at the project level."
    rationale: "Assigning these roles at the project level grants access to all service accounts, increasing the risk of misuse."
    audit:
      gcloud_command: "gcloud projects get-iam-policy PROJECT_ID --format=json | jq '.bindings[] | select(.role == \"roles/iam.serviceAccountUser\" or .role == \"roles/iam.serviceAccountTokenCreator\")'"
    remediation:
      steps:
        - "Revoke the Service Account User or Service Account Token Creator roles at the project level and assign them to specific service accounts instead."
    default_value: "By default, these roles are not assigned at the project level."
    references:
      - "https://cloud.google.com/iam/docs/service-accounts"

  - id: "1.8"
    title: "Ensure That Separation of Duties Is Enforced While Assigning Service Account Related Roles to Users (Automated)"
    profile_applicability: "Level 1"
    description: "Ensure separation of duties is enforced while assigning service account-related roles to users."
    rationale: "Separation of duties prevents a single user from having both Service Account Admin and Service Account User roles, reducing the risk of privilege escalation."
    audit:
      gcloud_command: "gcloud projects get-iam-policy [Project_ID] --format json | jq -r '[([\"Service_Account_Admin_and_User\"] | (., map(length*\"-\"))), ([.bindings[] | select(.role == \"roles/iam.serviceAccountAdmin\" or .role == \"roles/iam.serviceAccountUser\").members[]] | group_by(.) | map({User: ., Count: length}) | [] | select(.Count == 2).User | unique)] | [] | @tsv'"
    remediation:
      steps:
        - "Remove either the Service Account Admin or Service Account User role from users who have both roles assigned."
    default_value: "By default, users do not have both roles assigned simultaneously."
    references:
      - "https://cloud.google.com/iam/docs/service-accounts"

  # Network Configurations
  - id: "3.1"
    title: "Ensure That the Default Network Does Not Exist in a Project (Automated)"
    profile_applicability: "Level 2"
    description: "To prevent use of default network, a project should not have a default network."
    rationale: "The default network has preconfigured insecure firewall rules."
    audit:
      gcloud_command: "gcloud compute networks list"
    remediation:
      steps:
        - "Delete the default network if it exists."
    references:
      - "https://cloud.google.com/vpc/docs/using-firewalls"

  - id: "3.3"
    title: "Ensure That DNSSEC Is Enabled for Cloud DNS (Automated)"
    profile_applicability: "Level 1"
    description: "Ensure DNSSEC is enabled for Cloud DNS."
    rationale: "DNSSEC provides origin authentication and integrity verification of DNS data."
    audit:
      gcloud_command: "gcloud dns managed-zones describe [ZONE_NAME]"
    remediation:
      steps:
        - "Enable DNSSEC for the managed zone."
    references:
      - "https://cloud.google.com/dns/dnssec-config#enabling"

  - id: "4.9"
    title: "Ensure That Compute Instances Do Not Have Public IP Addresses (Automated)"
    profile_applicability: "Level 1"
    description: "Ensure that Compute Engine instances do not have public IP addresses."
    rationale: "Public IP addresses expose instances directly to the internet, increasing the attack surface."
    audit:
      gcloud_command: "gcloud compute instances list --filter='networkInterfaces[0].accessConfigs[0].natIP:*'"
    remediation:
      steps:
        - "Remove public IP addresses from instances by editing the instance configuration."
    references:
      - "https://cloud.google.com/compute/docs/ip-addresses/reserve-static-external-ip-address"

  - id: "4.10"
    title: "Ensure That VPC Flow Logs Are Enabled for Every Subnet (Automated)"
    profile_applicability: "Level 1"
    description: "Ensure that VPC flow logs are enabled for every subnet."
    rationale: "VPC flow logs provide visibility into network traffic, aiding in monitoring and forensic analysis."
    audit:
      gcloud_command: "gcloud compute networks subnets list --format=json | jq '.[] | select(.enableFlowLogs == false)'"
    remediation:
      steps:
        - "Enable VPC flow logs for each subnet."
    references:
      - "https://cloud.google.com/vpc/docs/using-flow-logs"

  - id: "4.11"
    title: "Ensure That Firewall Rules Do Not Allow Ingress From '0.0.0.0/0' to TCP Port 22 (Automated)"
    profile_applicability: "Level 1"
    description: "Ensure that firewall rules do not allow ingress from '0.0.0.0/0' to TCP port 22."
    rationale: "Allowing unrestricted SSH access increases the risk of unauthorized access."
    audit:
      gcloud_command: "gcloud compute firewall-rules list --filter='allowed[].ports[].list().contains(\"22\") AND sourceRanges.list().contains(\"0.0.0.0/0\")'"
    remediation:
      steps:
        - "Restrict SSH access to specific IP ranges or use Identity-Aware Proxy (IAP) for secure access."
    references:
      - "https://cloud.google.com/vpc/docs/firewalls"

  - id: "4.9"
    title: "Ensure That Compute Instances Do Not Have Public IP Addresses"
    profile_applicability: "Level 1"
    description: "Compute instances should not be configured to have external IP addresses."
    rationale: "To reduce your attack surface, Compute instances should not have public IP addresses. Instead, instances should be configured behind load balancers to minimize their exposure to the internet."
    impact: "Removing the external IP address from your Compute instance may cause some applications to stop working."
    audit:
      gcloud_command: "gcloud compute instances list --format=json"
      steps:
        - "The output should not contain an `accessConfigs` section under `networkInterfaces`. Note that the `natIP` value is present only for instances that are running or stopped but have a static IP address."
        - "For instances that are stopped and configured to have an ephemeral public IP address, the `natIP` field will not be present."
      exception: "Instances created by GKE should be excluded because some of them have external IP addresses and cannot be changed by editing the instance settings. These instances have names that start with 'gke-' and are labeled 'goog-gke-node'."
    remediation:
      steps:
        - "Go to the VM instances page by visiting: https://console.cloud.google.com/compute/instances."
        - "Click on the instance name to go to the Instance detail page."
        - "Click Edit."
        - "For each Network interface, ensure that External IP is set to None."
        - "Click Done and then click Save."
      gcloud_steps:
        - "Describe the instance properties: `gcloud compute instances describe <INSTANCE_NAME> --zone=<ZONE>`."
        - "Identify the access config name that contains the external IP address."
        - "Delete the access config: `gcloud compute instances delete-access-config <INSTANCE_NAME> --zone=<ZONE> --access-config-name <ACCESS_CONFIG_NAME>`."
    prevention:
      steps:
        - "Configure the 'Define allowed external IPs for VM instances' Organization Policy to prevent VMs from being configured with public IP addresses. Learn more at: https://console.cloud.google.com/orgpolicies/compute-vmExternalIpAccess."
    default_value: "By default, Compute instances have a public IP address."
    references:
      - "https://cloud.google.com/load-balancing/docs/backend-service#backends_and_external_ip_addresses"
      - "https://cloud.google.com/compute/docs/instances/connecting-advanced#sshbetweeninstances"
      - "https://cloud.google.com/compute/docs/instances/connecting-to-instance"
      - "https://cloud.google.com/compute/docs/ip-addresses/reserve-static-external-ip-address#unassign_ip"
      - "https://cloud.google.com/resource-manager/docs/organization-policy/org-policy-constraints"
