gcp:
  service_account_key_path: ${GCP_SERVICE_ACCOUNT_KEY_PATH}
  project_id: test-project-450103

logging:
  level: DEBUG
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: logs/app.log
  max_size: 10485760  # 10MB
  backup_count: 5

notifications:
  smtp:
    enabled: false
    sender_email: ${SMTP_SENDER_EMAIL}
    receiver_email: ${SMTP_RECEIVER_EMAIL}
    server: ${SMTP_SERVER}
    port: ${SMTP_PORT:-587}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    
  slack:
    enabled: false
    webhook_url: ${SLACK_WEBHOOK_URL}
    channel: ${SLACK_CHANNEL}

  jira:
    enabled: ${JIRA_ENABLED:-false}
    url: ${JIRA_URL}
    username: ${JIRA_USERNAME}
    api_token: ${JIRA_API_TOKEN}
    project_key: ${JIRA_PROJECT_KEY}
    issue_type: ${JIRA_ISSUE_TYPE:-Task}
    labels: ${JIRA_LABELS:-security,compliance}
    priority_field: ${JIRA_PRIORITY_FIELD:-priority}
    priority_mapping:
      Critical: Highest
      High: High
      Medium: Medium
      Low: Low

  servicenow:
    enabled: ${SERVICENOW_ENABLED:-false}
    instance_url: ${SERVICENOW_INSTANCE_URL}
    username: ${SERVICENOW_USERNAME}
    password: ${SERVICENOW_PASSWORD}
    table: ${SERVICENOW_TABLE:-incident}
    assignment_group: ${SERVICENOW_ASSIGNMENT_GROUP:-Security}
    category: ${SERVICENOW_CATEGORY:-Security}
    urgency_mapping:
      Critical: 1
      High: 2
      Medium: 3
      Low: 4

scanner:
  max_workers: 3
  timeout: 30
  batch_size: 100
  cis_benchmarks_file: config/cis_benchmarks.yaml

reporter:
  output_dir: reports
  formats:
    - csv
    - json
